AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mira and Joao API

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - Stage
      - Prod

Mappings:
  Prod:
    us-east-1:
      HostedZoneId: 'Z3SRU05LFQOORE'
      DomainName: api.miraandjoao.com
      DomainNameUi: "https://miraandjoao.com"
      CertificateArn: 'arn:aws:acm:us-east-1:890485269515:certificate/c6a6f2ac-027f-4fb3-8ec1-f70e9295db3b'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: app.lambdaHandler
    Runtime: nodejs8.10
    Timeout: 3
    Environment:
      Variables:
        HEADER_ACAO: !FindInMap [!Ref Environment, !Ref 'AWS::Region', DomainNameUi]
        USERS_TABLE_NAME: miraandjoao-users
        USERS_TABLE_USERTAG_INDEX_NAME: usertag-index
        RSVPS_TABLE_NAME:
          Ref: RsvpTable
  Api:
    Cors: !Join [ "", [ "'", !FindInMap [!Ref Environment, !Ref 'AWS::Region', DomainNameUi], "'" ] ]

Resources:

  RsvpTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: usertag
          AttributeType: S
        -
          AttributeName: timestamp
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: usertag
          KeyType: HASH
        -
          AttributeName: timestamp
          KeyType: RANGE
      TableName: !Sub ${Environment}-miraandjoao-rsvp
      Tags:
        -
          Key: Project
          Value: "miraandjoao.com"

  GetRsvpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-rsvp/
      Events:
        GetRsvp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /rsvp/{usertag}
            Method: get
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

  PostRsvpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: post-rsvp/
      Events:
        GetRsvp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /rsvp/{usertag}
            Method: post
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !FindInMap [!Ref Environment, !Ref 'AWS::Region', CertificateArn]
      DomainName: !FindInMap [!Ref Environment, !Ref 'AWS::Region', DomainName]

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref Environment

  APIDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !FindInMap [!Ref Environment, !Ref 'AWS::Region', HostedZoneId]
      RecordSets:
        - Name: !FindInMap [!Ref Environment, !Ref 'AWS::Region', DomainName]
          Type: A
          AliasTarget:
            DNSName: !GetAtt APIDomainName.DistributionDomainName
            HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases

Outputs:

  MiraAndJoaoApi:
    Description: "API Gateway endpoint URL for Get RSVP function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"

  GetRsvpFunction:
    Description: "GetRsvp Lambda Function ARN"
    Value: !GetAtt GetRsvpFunction.Arn

  GetRsvpFunctionIamRole:
    Description: "Implicit IAM Role created for GetRsvp function"
    Value: !GetAtt GetRsvpFunctionRole.Arn
